# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterReporteriOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  pod 'Kingfisher'

  # Pods for TwitterReporteriOS

  target 'TwitterReporteriOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterReporteriOSUITests' do
    # Pods for testing
  end

end


target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
end
