# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TabTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneSignal', '>= 2.11.2', '< 3.0'
  pod 'Kingfisher'
  pod 'Moya', '~> 14.0'


  # Pods for TabTest

  target 'TabTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabTestUITests' do
    # Pods for testing
  end

end
